# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d1e5ef0c55dbfe967924ab4184b5f26265e0c028d607a908f026d0523666f8b80bf6b0e830d62f7e07416fcea6cf8f1f5469c6dd7d66058ca7239bb7bb6c0c

test:
  secret_key_base: 5299b2be1041caa9e11ad24ea429e2a4819703ef1646ec81130d07be4087a1f4359cad215c9df07cc26155ca4d49c29efd5dd2c4676dc19425b04a11ce867bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
